export const ADD_CONTENT_REQUEST = "ADD_CONTENT_REQUEST";
export const ADD_CONTENT_SUCCESS = "ADD_CONTENT_SUCCESS";
export const ADD_CONTENT_ERROR = "ADD_CONTENT_ERROR";
export const ADD_CONTENT_RESET = "ADD_CONTENT_RESET";

export const GET_CONTENT_REQUEST = "GET_CONTENT_REQUEST";
export const GET_CONTENT_SUCCESS = "GET_CONTENT_SUCCESS";
export const GET_CONTENT_ERROR = "GET_CONTENT_ERROR";

export const UPDATE_CONTENT_REQUEST = "UPDATE_CONTENT_REQUEST";
export const UPDATE_CONTENT_SUCCESS = "UPDATE_CONTENT_SUCCESS";
export const UPDATE_CONTENT_ERROR = "UPDATE_CONTENT_ERROR";
export const UPDATE_CONTENT_RESET = "UPDATE_CONTENT_RESET";

export const UPDATE_COMMENTS_REQUEST = "UPDATE_COMMENTS_REQUEST";
export const UPDATE_COMMENTS_SUCCESS = "UPDATE_COMMENTS_SUCCESS";
export const UPDATE_COMMENTS_ERROR = "UPDATE_COMMENTS_ERROR";
export const UPDATE_COMMENTS_RESET = "UPDATE_COMMENTS_RESET";

export const UPDATE_COMMENTSCHILD_REQUEST = "UPDATE_COMMENTSCHILD_REQUEST";
export const UPDATE_COMMENTSCHILD_SUCCESS = "UPDATE_COMMENTSCHILD_SUCCESS";
export const UPDATE_COMMENTSCHILD_ERROR = "UPDATE_COMMENTSCHILD_ERROR";
export const UPDATE_COMMENTSCHILD_RESET = "UPDATE_COMMENTSCHILD_RESET";

export const GET_COMMMENT_SUCCESS = "GET_COMMMENT_SUCCESS";
export const GET_COMMMENT_ERROR = "GET_COMMMENT_ERROR";
