export const ADD_FRIENDS_REQUEST = "ADD_FRIENDS_REQUEST";
export const ADD_FRIENDS_SUCCESS = "ADD_FRIENDS_SUCCESS";
export const ADD_FRIENDS_ERROR = "ADD_FRIENDS_ERROR";
export const ADD_FRIENDS_RESET = "ADD_FRIENDS_RESET";

export const GET_FRIENDS_REQUEST = "GET_FRIENDS_REQUEST";
export const GET_FRIENDS_SUCCESS = "GET_FRIENDS_SUCCESS";
export const GET_FRIENDS_ERROR = "GET_FRIENDS_ERROR";

export const GET_NOTI_FRIENDS_REQUEST = "GET_NOTI_FRIENDS_REQUEST";
export const GET_NOTI_FRIENDS_SUCCESS = "GET_NOTI_FRIENDS_SUCCESS";
export const GET_NOTI_FRIENDS_ERROR = "GET_NOTI_FRIENDS_ERROR";

export const UPDATE_FRIENDS_REQUEST = "UPDATE_FRIENDS_REQUEST";
export const UPDATE_FRIENDS_SUCCESS = "UPDATE_FRIENDS_SUCCESS";
export const UPDATE_FRIENDS_ERROR = "UPDATE_FRIENDS_ERROR";
export const UPDATE_FRIENDS_RESET = "UPDATE_FRIENDS_RESET";
