export const ADD_MEESENGER_REQUEST = "ADD_MEESENGER_REQUEST";
export const ADD_MEESENGER_SUCCESS = "ADD_MEESENGER_SUCCESS";
export const ADD_MEESENGER_ERROR = "ADD_MEESENGER_ERROR";
export const ADD_MEESENGER_RESET = "ADD_MEESENGER_RESET";

export const GET_MEESENGER_REQUEST = "GET_MEESENGER_REQUEST";
export const GET_MEESENGER_SUCCESS = "GET_MEESENGER_SUCCESS";
export const GET_MEESENGER_ERROR = "GET_MEESENGER_ERROR";

export const UPDATE_MEESENGER_REQUEST = "UPDATE_MEESENGER_REQUEST";
export const UPDATE_MEESENGER_SUCCESS = "UPDATE_MEESENGER_SUCCESS";
export const UPDATE_MEESENGER_ERROR = "UPDATE_MEESENGER_ERROR";

export const DELETE_MEESENGER_REQUEST = "DELETE_MEESENGER_REQUEST";
export const DELETE_MEESENGER_SUCCESS = "DELETE_MEESENGER_SUCCESS";
export const DELETE_MEESENGER_ERROR = "DELETE_MEESENGER_ERROR";
